name: Destroy Infrastructure

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clear Terraform Cache
        run: |
          rm -rf .terraform
          rm -f .terraform.locl.hcl

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  # Make sure this matches your region

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Adjust based on your setup

      - name: Initialize Terraform
        run: terraform init -upgrade

      - name: Destroy Infrastructure
        run: terraform destroy -auto-approve
